### ISSUE TITLE
Winforms .ToImage() Outputting Images With Blank Tiles

### ISSUE THREAD

**Issue by ajos6183** [radioman/greatmaps#113]
The `.ToImage()` function does not appear to wait for the map data to be downloaded before the screenshot is taken. This results in images with blank tiles. Is there any existing capability that would allow GMaps to wait until the map is loaded?

**Comment by radioman** [comment]
https://github.com/radioman/greatmaps/blob/master/Demo.WindowsForms/Forms/StaticImage.cs

**Comment by ajos6183** [comment]
I ended up using the TilePrefetcher but what you are suggesting seems a lot faster, so i will switch to it. Thanks!
