### ISSUE TITLE
stop faking user agent

### ISSUE THREAD

**Issue by matkoniecz** [radioman/greatmaps#132]
According to https://github.com/radioman/greatmaps/blob/799f3a38a65350ff00c21acf9b88c96848bb3880/GMap.NET.Core/GMap.NET.MapProviders/GMapProvider.cs#L329-L336 this program fakes user agent in attempt to bypass usage limits

Please, stop doing this and start respecting usage limits instead.

**Comment by radioman** [comment]
Bla bla bla...
