### ISSUE TITLE
Zoom Level issue Opnstreetmap since 29 May 2019

### ISSUE THREAD

**Issue by olibara** [radioman/greatmaps#136]
Hello 
It seems that since 29 May the Tiles for Openstreetmap are not loaded anymore at some level
Anyone aware about some issue or behavior change ?
No issue on native OSM Site view ...
BTW : Because I love this Mapping tools I've also decided today to trigger two recrurent donation for RadioMan and OSM too
I guess we all should do it ...

**Comment by Firefishy** [comment]
I'm part of the OpenStreetMap sysadmin team and am not related to this project, hope you don't mind me commenting.

@olibara Thank you for the donation to the OpenStreetMap project.
The OpenStreetMap sysadmin teams (of which I am a part) are all unpaid volunteers.

GMAP.net fakes a few headers, most notably the User-Agent. Please review the Technical Usage Requirements here: https://operations.osmfoundation.org/policies/tiles/ there is a little bit extra to fix and your tiles will work again. Sorry for being vague.

**Comment by olibara** [comment]
Thanks a lot Firefish
I'll have a look on the source of GMAP.net and see what I can do if nobody else do some update
And I will definitely continue to support OSM and Radioman 
I've subscribed for both a  recurring donation

**Comment by jbavay** [comment]
Seems to be the use of tile url with http (and not https) which generate this 403 forbidden. 
an external test give 403 with http and correct answer with https.
Probably OSM server have enforce https usage.
So the url has to be changed.

**Comment by timminata** [comment]
We have also been experiencing this issue. Is there a workaround or do we need to submit a PR and get an update?

**Comment by jbavay** [comment]
Hi, 
Since we are using lately the nuget package provided by @judero01Col, I've made a pull request on their fork (https://github.com/judero01col/GMap.NET ) with the solution.
I guess they could push a pull request too.
Basically issue is due to http connection refused and the default referrer which generate a 418 error (The server identify itself as a teapot with such referrer... how strange. :) ). Since Tile Usage policy of OSM inform that this referrer has to be provided IF known, an empty referrer does not generate any error. So far.

**Comment by olibara** [comment]
Thanks Jo : Good job
Indeed I hope that we will not stay with two independent version of the same original solution made by Radioman
We would rather keep everything here (which seems to be the original although @juder01col did a good job and some fixes) and have a nugget publishing from here...
Any thought from the community ?

**Comment by radioman** [comment]
Thx for the fix, hopefully i'l update as possible...

**Comment by ignacioinnovo** [comment]
Hi everyone!

First of all, let me thank you for this great project! And also for the OpenStreetMap team!

I´m experiencing 403 error. I have updated to the last release but having the same problem. I have copied the code from the WinForms sample.

Has been working for 4 months without any problem.

Could anyone point me in the right direction, please?

Thank you in advanced!

**Comment by olibara** [comment]
Hello ignacioinnovo, 
Read the messages above : there is a fix on https://github.com/judero01col/GMap.NET  made by Jo
We all hope that rasioman will be able soon to align his native project with that fix

**Comment by ignacioinnovo** [comment]
Dear Olibara,

Thank you very much for your quick reply.

I am checking the link you gave me! Thanks!

And I also want to thank @radioman for maintaining this great project.

Have a nice day,
Ignacio

**Comment by olibara** [comment]
Hello ignacio thank you.
And thanks to Jo.
I also thanked Radioman and realized that it was worth making a donation.
I don't insist and I have no relationship with Radioman, but I have realized that too often we forget to support beautiful contributions like this one. 
Often we pay for much less simply because we can't do otherwise.
So I think that when you have the choice you have to be able to express yourself that you want to give a value! 

Translated with www.DeepL.com/Translator

**Comment by bacca87** [comment]
@radioman please update all nuget packages, in order to apply this fix to everybody!  #141

**Comment by radioman** [comment]
just checked, works fine for me, nothing to fix

**Comment by olibara** [comment]
Hello Radioman
Do you mean that you've update the Nugget ?
This was the request ..
The fix is indeed already applied but you are the one that can update the nugget
