### ISSUE TITLE
Net Framework 4.7.2

### ISSUE THREAD

**Issue by tomasdbrn** [radioman/greatmaps#147]
I'm using project net framework 4.7.2. Just in Release application end with error inicialization GMap.NET.WindowsForms.GMapControl..ctor()
Can you help me please?
Tom

**Comment by tomasdbrn** [comment]
I'm sorry net framework 4.5.2 WinForm

**Comment by tomasdbrn** [comment]
System.DllNotFoundException v GMap.NET.Core.dll

**Comment by tomasdbrn** [comment]
Do you know witch library I miss?

**Comment by patchbank** [comment]
First, you do not have to create a comment for each sentence. You can edit your comments by clicking the three dots in the upper right corner of your comments.

Second, please use the mentioned edit function to update the title and your first post with all neccessary informations.

---

`Do you know witch library I miss?`
It is literally telling you: `System.DllNotFoundException v GMap.NET.Core.dll`
