### ISSUE TITLE
407 Proxy Authentication Required

### ISSUE THREAD

**Issue by riverstream** [radioman/greatmaps#154]
I compiled the latest github solution as of 12/3/2019 in release mode.  I am receiving the following error when using GMap.NET.WindowsForms:

Exception: The remote server returned an error: (407) Proxy Authentication Required.

Yes, I am behind a proxy but it should automatically use the proxy settings already setup in IE (Internet Explorer).  This should be an automatic process just how Firefox and Chrome currently perform: These two web browsers automatically retrieve the current proxy settings from IE.  GMap.NET should also automatically use the proxy settings in IE without any further coding.

**Comment by rlkollman** [comment]
Not sure if you already determined how to get around this and are just requesting the project implement this automatically, or if you are seeking help bypassing this problem.  Here's how I resolved the same issue in VB .net:

`MapProviders.GMapProvider.WebProxy = Net.WebRequest.GetSystemWebProxy()
MapProviders.GMapProvider.WebProxy.Credentials = Net.CredentialCache.DefaultNetworkCredentials
`

I don't disagree that this could be implemented automatically, but I've noticed the System.Net library also does not seem to implement this automatically as I had to make similar modifications to my HTTP Requests for projects requesting simple web requests.
