### ISSUE TITLE
Update nuget package to latest tag

### ISSUE THREAD

**Issue by kjeremy** [radioman/greatmaps#16]
It looks like the latest package on nuget is 1.7.1 from 1/17/2015.  However the latest release in this repo is GreatMaps-v2015.23 from 12/29/2015.

**Comment by rheech** [comment]
Please update the NuGet package. Some features (OpenStreetMap returns 403 forbidden error) on v1.7.1 from NuGet.

**Comment by tomcheney** [comment]
This is causing me an issue too

**Comment by ahoefling** [comment]
This is an issue for us as well, we had to add direct project references after cloning the repository

**Comment by radioman** [comment]
done.
