### ISSUE TITLE
A few more features

### ISSUE THREAD

**Issue by faridcher** [radioman/greatmaps#18]
This is a great open source library and application. Thank you for that. But a few enhancement would make the demo application even better and comparable to its counterparts e.g. [Marble](https://github.com/KDE/marble). 
- bookmarks
- routing turn by turn textual result
- default extent (home)
- search suggestion once search query entered
- select geocoding engine (google, OSM, ...)
- select routing engine (google, ...)

I will try to add these features in future as soon as I got the time. Any feedback is appreciated.
Thanks

**Comment by radioman** [comment]
the main focus is map control, rendering tiles, db cache, map providers and custom projections, geocoding/routing is only optional. But any useful stuff is appreciated.

**Comment by roma2341** [comment]
i made attempts to rotate map several months ago but i couldn't do this because methods i found did nothing, please tell me anybody how to do this if it's possible.

**Comment by radioman** [comment]
in demo use 'A'/'Z' keys
