### ISSUE TITLE
Openstreetmap gives me this error

### ISSUE THREAD

**Issue by duiveldoder** [radioman/greatmaps#181]
Exception: The Request was aborted: Could not create SSL/TLS secure channel.

This is with the unaltered standard version. just loading the sln and start..

google satellite imagery and others work.. just openstreetmap gives me this

**Comment by dimka11** [comment]
Same issue, if you have the solution, please write. @duiveldoder

**Comment by duiveldoder** [comment]
yeah I solved it on my end - just update the net version

**Comment by duiveldoder** [comment]
Oh I close this issue - as upgrading the whole code to net 4.5 or higher solves the problem
