### ISSUE TITLE
WPF - Pinch Zoom 

### ISSUE THREAD

**Issue by ahoefling** [radioman/greatmaps#32]
Is there any plans to implement pinch zoom? This is something I need and have implemented this locally in our team fork and was hoping I could merge that change back here since it could be useful for other projects out there. If this is something that could be used in the main repo I can create a pull request.

**Comment by bacca87** [comment]
Please, send a pull request, but probably it will be completely ignored like the other ones...

**Comment by ahoefling** [comment]
I am working on cleaning up the code, but I just got pinch zoom effects working in WPF. I had to upgrade the version of .NET to be >= .NET 4.0 so I could access the proper ManipulationDelta Events. After I had access to those events I was super easy to get the delta and apply it to the Zoom property on GMapControl. I'm hoping to have this checked into our fork later today and then I will start creating my pull request.

**Comment by radioman** [comment]
p.s. nothing is ignored, it's on the list, if you want to move faster, fork and go ahead

**Comment by ahoefling** [comment]
I have this working and we are going to be using it in our fork once the team I am working with approves the Pull Request for the fork. I did my best to create it in a way where it won't break any existing code. Unfortunately a lot of the Map Panning features rely on mouse events that are tied into the core. I did not do a lot of digging (it could just be naming semantics) into the Core project but since we have tightly coupled on mouse vars and events I would say the PR I'll be submitting could be considered a little bit of a hack since I abused the back end in this way. The current touch implementation with the Stylus methods also relies on the mouse vars so I think what I did is okay. 

I will provide further documentation on the PR when I submit it here. If anyone is interested in seeing it right now you can view it here [https://github.com/surgeforward/greatmaps/pull/1](https://github.com/surgeforward/greatmaps/pull/1)
