### ISSUE TITLE
WPF Dragging issue

### ISSUE THREAD

**Issue by fsantiniabaca** [radioman/greatmaps#33]
I noticed a bug with the drag action of the Map, after opening a new Window and closing, it starts dragging automatically just by moving the Mouse over the map.
I could debug GMapControl.cs and there's an "if" on OnMouseMove method that checks if "cursor has moved beyond drag tolerance", this check calls "Core.BeginDrag" even if the user is not dragging the Map.

Note: I am working on a Pull Request.

Thanks

**Comment by fsantiniabaca** [comment]
This is the link to the Pull Request:
https://github.com/radioman/greatmaps/pull/34

**Comment by radioman** [comment]
thanks!
