### ISSUE TITLE
Support for Ground/Bitmap overlays

### ISSUE THREAD

**Issue by AliFlux** [radioman/greatmaps#36]
## TL;DR 

Is there any support for something like [`GroundOverlay`](https://developers.google.com/maps/documentation/javascript/examples/groundoverlay-simple) in GMap.net?

## Description

I need to put some simple bitmaps on my map, without using any custom map provider. Is there any built-in support for this? If not, then is there any hack?

**Comment by radioman** [comment]
https://github.com/radioman/greatmaps/tree/master/Tools/MapCruncher

**Comment by AliFlux** [comment]
Is there a way to add bitmap *over* a map already rendered.

**Comment by radioman** [comment]
check https://github.com/radioman/greatmaps/tree/master/Testing/Demo.Clouds
