### ISSUE TITLE
Using single Bitmap as map source

### ISSUE THREAD

**Issue by AliFlux** [radioman/greatmaps#37]
Is there a way to use a single large image as a map source? I am looking for a map provider that uses a single image, lat/lon, zoom, and bearing.

## Alternate idea

Is there a way to convert a single image into a set of map tiles that can be picked by maps? I came across  [MapTiler](https://www.maptiler.com/), but it is paid and close-sourced.

**Comment by radioman** [comment]
check https://github.com/radioman/greatmaps/tree/master/Tools/MapCruncher

**Comment by AliFlux** [comment]
I'm looking for a simple API/functionality, not exactly an external program.

**Comment by radioman** [comment]
mapcruncher can convert your bitmap to tiles, then you can use them in gmap
