### ISSUE TITLE
Marker disappear after change tab

### ISSUE THREAD

**Issue by samuraitruong** [radioman/greatmaps#39]
Hi everyone, 

I would ask if anybody has similar issue as i am having 

I use a GmapControl in a main tab, it working fine if I don't change tab  page. Whenever I switch tab page and switch back to map tap, all markers disappear, but the new marker add after switch back they still display fine?

Sorry if this duplicate with other issue?

**Comment by radioman** [comment]
;/ any demo?

**Comment by samuraitruong** [comment]
I fixed issed, my mistake when use sample code, please close this
