### ISSUE TITLE
Google routing

### ISSUE THREAD

**Issue by mkuhic** [radioman/greatmaps#4]
Few days ago .GoogleMapProvider.Instance.GetRoute stopped working.
Any ideas?

The only working provider for routing (for me)  is OpenStreetMapProvider.Instance.GetRoute

Also bing and yahoo don't seem to work any more.

**Comment by radioman** [comment]
you can use direction api instead

**Comment by mkuhic** [comment]
I'm trying right now but GetDirections don't seem to return a MapRoute type.

**Comment by mkuhic** [comment]
Found out:
GMap.NET.MapProviders.GoogleMapProvider.Instance.GetDirections(ret, sta, sto, False, False, False, False, False)
r = New GMapRoute(ret.Route, "My route")

But what about Bing and yahoo routing?

**Comment by radioman** [comment]
it's open project, feel free to fix it ;}

**Comment by roma2341** [comment]
I'm trying to rotate map using Bearing. I can't change Beraing value from Designer and when i change Bearing in my code nothing happen. What i do wrong ?
