### ISSUE TITLE
Updating marker's image

### ISSUE THREAD

**Issue by mustaphos** [radioman/greatmaps#42]
Hi.
I want to update the marker's image after I add it. I tried to change location of the marker and it is OK but image is marker's public property. How can I solve this problem. I need to change the icon image continously. For example I need to rotate an airplane icon. 
Thanks...

**Comment by radioman** [comment]
check flight demo: https://github.com/radioman/greatmaps/blob/master/Demo.WindowsForms/Forms/MainForm.cs#L322

server might be down or not up to date, but the code works, -> '(marker as GMarkerArrow).Bearing =...'

**Comment by mustaphos** [comment]
The type or namespace name 'GMarkerArrow' could not be found.
