### ISSUE TITLE
How to add two or more maps onetime

### ISSUE THREAD

**Issue by weskerjiang** [radioman/greatmaps#43]
at this time,only a provider can use to show the map ,but i want add two or more maps onetime,so how can i do this?

**Comment by radioman** [comment]
do you mean overlay?

**Comment by weskerjiang** [comment]
no,i mean provider, for example,i have providerA,providerB,i want mapControl shows providerA and providerB and providerB is over providerA,just like many other mapControls,they called layer,not the overlay,and the mapcontrol.provider = XXXXX,it can only accept one provider,i want many providers shows onetime,not switch.TKS

**Comment by radioman** [comment]
i guess you are talking about transparent layer on top some base layer, there are few examples already:

https://github.com/radioman/greatmaps/blob/master/GMap.NET.Core/GMap.NET.MapProviders/Google/GoogleHybridMapProvider.cs#L51
