### ISSUE TITLE
Tiles not loading at a certain zoom level

### ISSUE THREAD

**Issue by AliFlux** [radioman/greatmaps#48]
Hi.

I'm using the WPF control with `BingSatelliteMapProvider`. When I initialize the control with zoom level <= 19, the map works perfectly. But when I do it with zoom >= 20, the tiles won't load. Unless you zoom out one level and then zoom in again. This is probably due to the max zoom level of Bing Maps API. At a certain level, it stops giving the response.

Can I derive a new class from `BingSatelliteMapProvider` and add a hackish routine that checks if the zoom level is 20+, it gives the scaled up version of level 19. If so, can you give any pointers?

Thanks.

CC: @radioman

**Comment by radioman** [comment]
scaling is integrated, but you have to have data in cache already to be able to 'scale', thats why you start at low level, then the data for 'scaling' is ready, then if you have no data on next level, scaling kicks in
