### ISSUE TITLE
Custom tooltips

### ISSUE THREAD

**Issue by blackbirdsr71br** [radioman/greatmaps#49]
It is an excellent library, there is some way that the tooltip can be added images and tables as the following example.
![pantalla](https://cloud.githubusercontent.com/assets/24237848/24280945/6db850bc-101a-11e7-9598-3516ddde3387.png)

Thank you

**Comment by fengguangle** [comment]
I think it can be implemented in WPF.
Because in WPF,the tooltip is displayed by a popup. like:
```
Popup.PlacementTarget = this;
            Popup.Placement = PlacementMode.Right;//.Top;//.Mouse;
            {
                Label.Background = Brushes.White;
                Label.Foreground = Brushes.DarkBlue;
                Label.BorderBrush = new SolidColorBrush(Color.FromArgb(155, 0xF0, 0xF8, 0xFF));
                Label.BorderThickness = new Thickness(3);
                Label.Padding = new Thickness(3);
                Label.FontSize = 12;
                Label.Content = title;
            }
            Popup.Child = Label;
```
So, you can change the Label element to your user control. And the user control is designed to the style you want.
