### ISSUE TITLE
Get an overlay ion one request

### ISSUE THREAD

**Issue by ChFreund** [radioman/greatmaps#50]
Is it possible to implement the possibility to get an overlay in one request?
I have a provider, that breaks the labels if I pull every map matrix element for himself.

I can get the background in multiple requests splitted in the tile matrix.
I want to get other layers in another like GoogleHybridMapProvider.
But I need to get the overlay (for streetlabels, POIs and so on) in one request. Not splitted in a Martrix.
Regards,

Christian.

**Comment by radioman** [comment]
some providers have merged layers, some dont

**Comment by ChFreund** [comment]
Yes I know. :-)
But is there an event, I can use to do something after the background tile layers to make the overlay?
Or can I get an overlay in one step not in the matrix?
Or is it possible to get the size of the matrix over all?

**Comment by radioman** [comment]
https://github.com/radioman/greatmaps/blob/master/GMap.NET.WindowsForms/GMap.NET.WindowsForms/GMapControl.cs#L972
