### ISSUE TITLE
how to remove the center cross's "debug build" text

### ISSUE THREAD

**Issue by weskerjiang** [radioman/greatmaps#51]
how to remove it?thanks

**Comment by radioman** [comment]
https://github.com/radioman/greatmaps/blob/master/GMap.NET.WindowsForms/GMap.NET.WindowsForms/GMapControl.cs#L171

**Comment by weskerjiang** [comment]
not the red cross but the blue cross,showcenter just disable the red cross,the blue cross with "debug build"

**Comment by radioman** [comment]
use release build
