### ISSUE TITLE
Split the gmap.net database

### ISSUE THREAD

**Issue by siyad4ever** [radioman/greatmaps#52]
I have been using this great program for a few months and now i have a very large database in my app. Can anyone help me how to extract / split a small location database cache from a very large gmdb database...

**Comment by radioman** [comment]
multiply gmdb is supported, for migration you can use https://www.yunqa.de/delphi/products/sqlitespy/index

**Comment by siyad4ever** [comment]
How can i get the X and Y values of a selected area (alt key pressed) for every zoom levels (mostly 12-19)

**Comment by radioman** [comment]
https://github.com/radioman/greatmaps/blob/master/Demo.WindowsForms/Forms/MainForm.cs#L1607
