### ISSUE TITLE
MouseDoubleClick event trigger the MouseClick event and so on

### ISSUE THREAD

**Issue by weskerjiang** [radioman/greatmaps#56]
when i double click the mapcontrol  the event trigger order is
mouse down --> mouse click --> mouse up --> mouse down --> mouse double click --> mouse up
i just want trigger the "double click" event but i still need other event ,how to do that?

**Comment by fengguangle** [comment]
It's really troublesome.
My usual solution is setting many flags to tell what I wangt to do in one event.

**Comment by radioman** [comment]
thanks!
