### ISSUE TITLE
Access modifier for Position

### ISSUE THREAD

**Issue by galakt** [radioman/greatmaps#6]
What the point of use Core.position (field public PointLatLng position) insteed Core.Position (public property) in https://github.com/radioman/greatmaps/blob/master/GMap.NET.WindowsForms/GMap.NET.WindowsForms/GMapControl.cs?

Can we use public property and make field is private?

**Comment by radioman** [comment]
whats the point of property, its internal anayway

**Comment by galakt** [comment]
Yes, it is internal, but my opinion that public property and public field at the same time looks messy, when you want change something. Also it can make source code less readable for others and opportunity to mistake, because you can miss that access to Core.position will not fire OnCurrentPositionChanged. What do you think? Anyway i like greatmap project.

**Comment by radioman** [comment]
not many read that code, thanks for that! You can try to make a fork for your ideas
