### ISSUE TITLE
GDI + Error

### ISSUE THREAD

**Issue by RunAndFly** [radioman/greatmaps#67]
Hello,
I use  the 1.75 version from NuGet and only on RDP Session on 2008 R2 server.
when the session is disconnected ( the application is still running)
I got a generic GDI+ error on the clear method when I came back to the RDP session 

nota : on 2012 R2 the error don't exists

Stack : à System.Drawing.Graphics.Clear(Color color)
à GMap.NET.WindowsForms.GMapControl.DrawGraphics(Graphics g)
à GMap.NET.WindowsForms.GMapControl.OnPaint(PaintEventArgs e)
à System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
à System.Windows.Forms.Control.WmPaint(Message& m)
à System.Windows.Forms.Control.WndProc(Message& m)
à System.Windows.Forms.ScrollableControl.WndProc(Message& m)
à System.Windows.Forms.ContainerControl.WndProc(Message& m)
à System.Windows.Forms.UserControl.WndProc(Message& m)
à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Any idea or workarround

**Comment by RunAndFly** [comment]
Link  about RDP and clear()

[https://social.msdn.microsoft.com/Forums/windows/en-US/08eedbf7-db24-4106-9b7a-cd17a792015d/a-generic-error-occurred-in-gdi-at-systemdrawinggraphicsclearcolor-color-in-net-40?forum=winforms](url)
[https://www.pcreview.co.uk/threads/re-gdi-error-with-remote-desktop.2893741/](url)

**Comment by RunAndFly** [comment]
Link about RDP and clear()

https://social.msdn.microsoft.com/Forums/windows/en-US/08eedbf7-db24-4106-9b7a-cd17a792015d/a-generic-error-occurred-in-gdi-at-systemdrawinggraphicsclearcolor-color-in-net-40?forum=winforms
https://www.pcreview.co.uk/threads/re-gdi-error-with-remote-desktop.2893741/

**Comment by radioman** [comment]
"The behaviour of GDI+ is by design and we could ignore the exception
occurring in this case. To do this, override the
TabControl.OnPaintBackground method and catch the exception in the override
method and then ingore it."
