### ISSUE TITLE
Confusion about the project

### ISSUE THREAD

**Issue by emresebat** [radioman/greatmaps#76]
Hi

The old codeplex site show this repository but here is another repository very similar to greatmaps:
[GMap.NET](https://github.com/judero01col/GMap.NET)
It has also a nuget package latest version 1.8.0, so is that a fork and which one is the active one?

Thanks.

**Comment by emresebat** [comment]
Okk so you mean that's not a fork, it's a clone wihout asking permission from @radioman ?

**Comment by luxiaoxun** [comment]
@emresebat 
Not sure if @emresebat got permission. But I guess it's OK if someone is interested in working on this project.  I kept one version forked from this project for myself. I even pulled a request to this project one year ago but no response from @radioman .

**Comment by emresebat** [comment]
Thanks @luxiaoxun 

Of course it's ok to fork it but this seems a copy without even mentioning the original repo.
