### ISSUE TITLE
There's no license?

### ISSUE THREAD

**Issue by CS-Tao** [radioman/greatmaps#83]
The license for this repository is not added. Can I use the source code in my repository? 😄

**Comment by radioman** [comment]
Yep, https://github.com/radioman/greatmaps/blob/master/Info/License.txt

**Comment by guggy** [comment]
What about files such as 
https://github.com/radioman/greatmaps/blob/master/GMap.NET.WindowsMobile/GMap.NET.GPS/Utils.cs
?
