### ISSUE TITLE
Mapy.cz not work correctly

### ISSUE THREAD

**Issue by tomasdbrn** [radioman/greatmaps#84]
Hello,
when i using GMap.NET.MapProviders.CzechMapProvider.Instance, map tiles is not loaded. First loading is ok, but when i move with map, then i get white place. Google, StreetView work ok.
Can you help me please?
Tom

**Comment by jelinj8** [comment]
Hello,
this fixed Czech maps for me:
https://github.com/jelinj8/greatmaps/commit/76f7672f277b19fa23aa929e50707df3cc624f9e
Jakub
